### ISSUE TITLE
Question : What to do ? 

### ISSUE THREAD

**Issue by toutouff** [EndeavourOS-Community-Editions/hyprland#1]
I made a fresh installation from sway then proceed to install hypr after that I use the package list and hyprconf to set up the DE to work globally this config, and it was not working really nice 
so after that I have rebased my config on another GitHub user (who also use endavourOS) and every thing went better like really well so 
 my question is  : 
What to do so that other starter can easily understand and actually use Hypr 

> I also can't accurately label it with the question label or tag

**Comment by killajoe** [comment]
this is still work in progress and not official released ;)

**Comment by toutouff** [comment]
@mslauson 1ams1mp1e i use balcony branch and i love the rofi config and the key config and it was one of the recomended config buy hyprland

**Comment by killajoe** [comment]
you can contribute by fork and pull request. or contact the maintainers..
