### ISSUE TITLE
icons

### ISSUE THREAD

**Issue by killajoe** [EndeavourOS-Community-Editions/hyprland#2]
https://github.com/EndeavourOS-Community-Editions/hyprland/blob/6e2d6af1cc70384604215e3fa1221221bb5a4827/packages-repository.txt#L15

I would recommend to use qogir as it is more complete and mainatined.. 

```
local/eos-qogir-icons 4-2
    A colorful design icon theme for linux desktops
```

**Comment by rudy-in** [comment]
hey there , do not worry we are gonna start over this time with your guidance with the themes and stuff
